### ISSUE TITLE
how do you compile this

### ISSUE THREAD

**Issue by thacuber2a03** [kiedtl/cel7ce#1]
koio's compilation treats warnings as errors, so that's one problem.
I manually compile it, then I run `make` again, and it complains about `lua5.3` not being installed.
I install it, and it finally fails with a ton of linker errors.
how am I supposed to compile this??

**Comment by kiedtl** [comment]
Part of the issue is that I had developed cel7ce on a hyperspecific arm7 musl setup, and hadn't tested the build script on other machines. Hence some weird static linking nonsense.

The other part of the issue is that cel7ce isn't yet ready for use, it's still alpha software. In fact, I intend to tear out a bunch of features I added, after realizing they don't fit in with the spirit of the original cel7. All, of course, after I eventually return to working on this project, and who knows when that will be.

I've fixed the build issues (I think), but please be aware that this is pre-alpha-quality stuff.
